name: Android Build and Release

on:
  workflow_dispatch:
    inputs:
      release_name:
        required: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Validate Gradle Wrapper
      uses: gradle/wrapper-validation-action@v1

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Gradle assembleSwProdRelease
      uses: gradle/gradle-build-action@v2
      with:
        arguments: assembleSwProdRelease

    # https://stackoverflow.com/questions/69164423/glob-markdown-files-on-github-action-only-returns-docs-folder
    # https://unix.stackexchange.com/questions/81349/how-do-i-use-find-when-the-filename-contains-spaces
    - name: Create release
      run: find "app/build/outputs/apk/swProd/release/" -name "*.apk" -print0 | xargs -0 gh release create "$RELEASE_NAME"
      env:
       GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
       RELEASE_NAME: ${{github.event.inputs.release_name}}
