name: Reproducible Build Check

on:
  #schedule:
  #  - cron: '0 5 * * *'
  workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build image
      run: cd reproducible-builds && docker build -t signal-android . && cd ..

    - name: Test build
      run: docker run --rm -v $(pwd):/project -w /project signal-android ./gradlew clean assemblePlayProdRelease
